GetErrExpectedCount Proto
GetErrExpectedSize Proto index:Dword
GetErrExpectedStr Proto index:Dword, addrStr:Dword
GetErrLastTokenSize Proto
GetErrLastToken Proto tokenData:Dword
GetCurrentLine Proto
GetCurrentColumn Proto
GetRTokenCount Proto
GetRTokenData Proto index:Dword, addrStr:Dword
GetRTokenDataSize Proto index:Dword
GetRSymbolIndex Proto
ResetParser Proto
LoadProgramText Proto ProgramText:Dword
LoadProgramFile Proto ProgramFile:Dword 
Parse Proto
LoadGrammarFile Proto GrammarFile:Dword
IsGrammarLoaded Proto